using Microsoft.EntityFrameworkCore;
using PulsePoll.Domain.Entities;
using PulsePoll.Domain.Enums;
using PulsePoll.Infrastructure.Persistence;

namespace PulsePoll.Infrastructure;

public static class DbSeeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await SeedLookups(db);
        await SeedCitiesAndDistricts(db);
        await SeedTaxOfficesAsync(db);
        await SeedMessageTemplatesAsync(db);
    }

    private static async Task SeedLookups(AppDbContext db)
    {
        if (!await db.EducationLevels.AnyAsync())
        {
            // TÜAD SES 2012 — 9 eğitim seviyesi (OrderIndex SES tablosundaki kolon pozisyonuna karşılık gelir)
            db.EducationLevels.AddRange(
                new EducationLevel { Name = "Okur-Yazar Değil",                        OrderIndex = 1 },
                new EducationLevel { Name = "Okur-Yazar (İlkokul Terk)",               OrderIndex = 2 },
                new EducationLevel { Name = "İlkokul Mezunu",                          OrderIndex = 3 },
                new EducationLevel { Name = "Ortaokul / İlköğretim Mezunu",            OrderIndex = 4 },
                new EducationLevel { Name = "Lise Terk",                               OrderIndex = 5 },
                new EducationLevel { Name = "Lise / Dengi Okul Mezunu",                OrderIndex = 6 },
                new EducationLevel { Name = "Üniversite Terk / Ön Lisans Mezunu",      OrderIndex = 7 },
                new EducationLevel { Name = "Üniversite (Lisans) Mezunu",              OrderIndex = 8 },
                new EducationLevel { Name = "Yüksek Lisans / Doktora Mezunu",          OrderIndex = 9 }
            );
            await db.SaveChangesAsync();
        }

        if (!await db.SocioeconomicStatuses.AnyAsync())
        {
            db.SocioeconomicStatuses.AddRange(
                new SocioeconomicStatus { Name = "A  — Üst",           Code = "A",  SortOrder = 1 },
                new SocioeconomicStatus { Name = "B  — Üst Orta",      Code = "B",  SortOrder = 2 },
                new SocioeconomicStatus { Name = "C1 — Orta",          Code = "C1", SortOrder = 3 },
                new SocioeconomicStatus { Name = "C2 — Alt Orta",      Code = "C2", SortOrder = 4 },
                new SocioeconomicStatus { Name = "D  — Alt",           Code = "D",  SortOrder = 5 },
                new SocioeconomicStatus { Name = "E  — En Alt",        Code = "E",  SortOrder = 6 }
            );
            await db.SaveChangesAsync();
        }

        if (!await db.LSMSocioeconomicStatuses.AnyAsync())
        {
            db.LSMSocioeconomicStatuses.AddRange(
                new LSMSocioeconomicStatus { Name = "LSM1", Code = "LSM1" },
                new LSMSocioeconomicStatus { Name = "LSM2", Code = "LSM2" },
                new LSMSocioeconomicStatus { Name = "LSM3", Code = "LSM3" },
                new LSMSocioeconomicStatus { Name = "LSM4", Code = "LSM4" },
                new LSMSocioeconomicStatus { Name = "LSM5", Code = "LSM5" }
            );
            await db.SaveChangesAsync();
        }

        if (!await db.Professions.AnyAsync())
        {
            db.Professions.AddRange(
                new Profession { Name = "İşsiz",                                              Code = "ISSZ" },
                new Profession { Name = "Ev Hanımı",                                          Code = "EVHN" },
                new Profession { Name = "Öğrenci",                                            Code = "OGRN" },
                new Profession { Name = "Ücretli Çalışan (Devlet)",                           Code = "YVML" },
                new Profession { Name = "Ücretli Çalışan (Özel Sektör)",                      Code = "OZCL" },
                new Profession { Name = "Kendi Hesabına Çalışan",                             Code = "KMCL" },
                new Profession { Name = "Özel Sektör Küçük İşveren",                         Code = "OZSU" },
                new Profession { Name = "Kamu Sektörü Küçük İşveren",                        Code = "KMSU" },
                new Profession { Name = "Özel Sektör Büyük İşveren / Üst Düzey Yönetici",    Code = "OZYN" },
                new Profession { Name = "Kamu Sektörü Büyük İşveren / Üst Düzey Yönetici",   Code = "KMYN" },
                new Profession { Name = "TSK Personeli",                                      Code = "TSKP" },
                new Profession { Name = "Doktor",                                             Code = "DKTR" },
                new Profession { Name = "Avukat",                                             Code = "AVKT" },
                new Profession { Name = "Mühendis / Mimar",                                   Code = "MMHD" },
                new Profession { Name = "Akademisyen",                                        Code = "AKDM" },
                new Profession { Name = "Çiftçi",                                             Code = "CFTC" },
                new Profession { Name = "Fırıncı / Lokantacı",                               Code = "FRLC" },
                new Profession { Name = "Esnaf",                                              Code = "ESNF" },
                new Profession { Name = "Serbest Meslek (Küçük Ölçekli)",                     Code = "SRKS" },
                new Profession { Name = "Eczacı / Mali Müşavir / Serbest Meslek (Büyük)",     Code = "ECZC" },
                new Profession { Name = "Mali Müşavir",                                       Code = "MLMS" },
                new Profession { Name = "Emekli (Çalışmıyor)",                               Code = "EMKL" },
                new Profession { Name = "Emekli (Çalışıyor)",                                Code = "EMKC" },
                new Profession { Name = "Diğer",                                              Code = "DIGR" }
            );
            await db.SaveChangesAsync();
        }

        if (!await db.Banks.AnyAsync())
        {
            db.Banks.AddRange(
                new Bank { Name = "Akbank",                  Code = "AKBANK"   },
                new Bank { Name = "Albaraka Türk",           Code = "ALBARAKA" },
                new Bank { Name = "Alternatifbank",          Code = "ALTBANK"  },
                new Bank { Name = "Anadolubank",             Code = "ANADOLU"  },
                new Bank { Name = "Burgan Bank",             Code = "BURGAN"   },
                new Bank { Name = "Denizbank",               Code = "DENIZ"    },
                new Bank { Name = "Fibabanka",               Code = "FIBA"     },
                new Bank { Name = "Garanti BBVA",            Code = "GARANTI"  },
                new Bank { Name = "Halk Katılım",            Code = "HKTLM"    },
                new Bank { Name = "Halkbank",                Code = "HALK"     },
                new Bank { Name = "HSBC",                    Code = "HSBC"     },
                new Bank { Name = "ING Bank",                Code = "ING"      },
                new Bank { Name = "Kuveyt Türk",             Code = "KUVEYT"   },
                new Bank { Name = "Odea Bank",               Code = "ODEA"     },
                new Bank { Name = "QNB Finansbank",          Code = "QNB"      },
                new Bank { Name = "Şekerbank",               Code = "SEKER"    },
                new Bank { Name = "TEB",                     Code = "TEB"      },
                new Bank { Name = "Türkiye Finans",          Code = "TRFINANS" },
                new Bank { Name = "Türkiye İş Bankası",      Code = "ISBANK"   },
                new Bank { Name = "Vakıf Katılım",           Code = "VKTLM"    },
                new Bank { Name = "VakıfBank",               Code = "VAKIF"    },
                new Bank { Name = "Yapı Kredi",              Code = "YKRN"     },
                new Bank { Name = "Ziraat Bankası",          Code = "ZIRAAT"   },
                new Bank { Name = "Ziraat Katılım",          Code = "ZKTLM"    }
            );
            await db.SaveChangesAsync();
        }
    }

    private static async Task SeedCitiesAndDistricts(AppDbContext db)
    {
        if (await db.Cities.AnyAsync())
            return;

        var cities = new List<City>
        {
            new City { Name = "ADANA", PlateCode = 1 },
            new City { Name = "ADIYAMAN", PlateCode = 2 },
            new City { Name = "AFYONKARAHİSAR", PlateCode = 3 },
            new City { Name = "AĞRI", PlateCode = 4 },
            new City { Name = "AMASYA", PlateCode = 5 },
            new City { Name = "ANKARA", PlateCode = 6 },
            new City { Name = "ANTALYA", PlateCode = 7 },
            new City { Name = "ARTVİN", PlateCode = 8 },
            new City { Name = "AYDIN", PlateCode = 9 },
            new City { Name = "BALIKESİR", PlateCode = 10 },
            new City { Name = "BİLECİK", PlateCode = 11 },
            new City { Name = "BİNGÖL", PlateCode = 12 },
            new City { Name = "BİTLİS", PlateCode = 13 },
            new City { Name = "BOLU", PlateCode = 14 },
            new City { Name = "BURDUR", PlateCode = 15 },
            new City { Name = "BURSA", PlateCode = 16 },
            new City { Name = "ÇANAKKALE", PlateCode = 17 },
            new City { Name = "ÇANKIRI", PlateCode = 18 },
            new City { Name = "ÇORUM", PlateCode = 19 },
            new City { Name = "DENİZLİ", PlateCode = 20 },
            new City { Name = "DİYARBAKIR", PlateCode = 21 },
            new City { Name = "EDİRNE", PlateCode = 22 },
            new City { Name = "ELAZIĞ", PlateCode = 23 },
            new City { Name = "ERZİNCAN", PlateCode = 24 },
            new City { Name = "ERZURUM", PlateCode = 25 },
            new City { Name = "ESKİŞEHİR", PlateCode = 26 },
            new City { Name = "GAZİANTEP", PlateCode = 27 },
            new City { Name = "GİRESUN", PlateCode = 28 },
            new City { Name = "GÜMÜŞHANE", PlateCode = 29 },
            new City { Name = "HAKKARİ", PlateCode = 30 },
            new City { Name = "HATAY", PlateCode = 31 },
            new City { Name = "ISPARTA", PlateCode = 32 },
            new City { Name = "MERSİN", PlateCode = 33 },
            new City { Name = "İSTANBUL", PlateCode = 34 },
            new City { Name = "İZMİR", PlateCode = 35 },
            new City { Name = "KARS", PlateCode = 36 },
            new City { Name = "KASTAMONU", PlateCode = 37 },
            new City { Name = "KAYSERİ", PlateCode = 38 },
            new City { Name = "KIRKLARELİ", PlateCode = 39 },
            new City { Name = "KIRŞEHİR", PlateCode = 40 },
            new City { Name = "KOCAELİ", PlateCode = 41 },
            new City { Name = "KONYA", PlateCode = 42 },
            new City { Name = "KÜTAHYA", PlateCode = 43 },
            new City { Name = "MALATYA", PlateCode = 44 },
            new City { Name = "MANİSA", PlateCode = 45 },
            new City { Name = "KAHRAMANMARAŞ", PlateCode = 46 },
            new City { Name = "MARDİN", PlateCode = 47 },
            new City { Name = "MUĞLA", PlateCode = 48 },
            new City { Name = "MUŞ", PlateCode = 49 },
            new City { Name = "NEVŞEHİR", PlateCode = 50 },
            new City { Name = "NİĞDE", PlateCode = 51 },
            new City { Name = "ORDU", PlateCode = 52 },
            new City { Name = "RİZE", PlateCode = 53 },
            new City { Name = "SAKARYA", PlateCode = 54 },
            new City { Name = "SAMSUN", PlateCode = 55 },
            new City { Name = "SİİRT", PlateCode = 56 },
            new City { Name = "SİNOP", PlateCode = 57 },
            new City { Name = "SİVAS", PlateCode = 58 },
            new City { Name = "TEKİRDAĞ", PlateCode = 59 },
            new City { Name = "TOKAT", PlateCode = 60 },
            new City { Name = "TRABZON", PlateCode = 61 },
            new City { Name = "TUNCELİ", PlateCode = 62 },
            new City { Name = "ŞANLIURFA", PlateCode = 63 },
            new City { Name = "UŞAK", PlateCode = 64 },
            new City { Name = "VAN", PlateCode = 65 },
            new City { Name = "YOZGAT", PlateCode = 66 },
            new City { Name = "ZONGULDAK", PlateCode = 67 },
            new City { Name = "AKSARAY", PlateCode = 68 },
            new City { Name = "BAYBURT", PlateCode = 69 },
            new City { Name = "KARAMAN", PlateCode = 70 },
            new City { Name = "KIRIKKALE", PlateCode = 71 },
            new City { Name = "BATMAN", PlateCode = 72 },
            new City { Name = "ŞIRNAK", PlateCode = 73 },
            new City { Name = "BARTIN", PlateCode = 74 },
            new City { Name = "ARDAHAN", PlateCode = 75 },
            new City { Name = "IĞDIR", PlateCode = 76 },
            new City { Name = "YALOVA", PlateCode = 77 },
            new City { Name = "KARABÜK", PlateCode = 78 },
            new City { Name = "KİLİS", PlateCode = 79 },
            new City { Name = "OSMANİYE", PlateCode = 80 },
            new City { Name = "DÜZCE", PlateCode = 81 },
        };

        db.Cities.AddRange(cities);
        await db.SaveChangesAsync();

        var cityMap = await db.Cities.ToDictionaryAsync(c => c.PlateCode, c => c.Id);

        var districtSeeds = new List<DistrictSeed>
        {
            new DistrictSeed(1, "Şakirpaşa Havalimanı"),
            new DistrictSeed(1, "ÇUKUROVA"),
            new DistrictSeed(1, "SARIÇAM"),
            new DistrictSeed(1, "İMAMOĞLU"),
            new DistrictSeed(1, "ALADAĞ"),
            new DistrictSeed(1, "YÜREĞİR"),
            new DistrictSeed(1, "YUMURTALIK"),
            new DistrictSeed(1, "TUFANBEYLİ"),
            new DistrictSeed(1, "SAİMBEYLİ"),
            new DistrictSeed(1, "POZANTI"),
            new DistrictSeed(1, "KOZAN"),
            new DistrictSeed(1, "KARATAŞ"),
            new DistrictSeed(1, "KARAİSALI"),
            new DistrictSeed(1, "FEKE"),
            new DistrictSeed(1, "CEYHAN"),
            new DistrictSeed(1, "SEYHAN"),
            new DistrictSeed(2, "Adıyaman Havalimanı"),
            new DistrictSeed(2, "TUT"),
            new DistrictSeed(2, "SİNCİK"),
            new DistrictSeed(2, "SAMSAT"),
            new DistrictSeed(2, "KAHTA"),
            new DistrictSeed(2, "GÖLBAŞI"),
            new DistrictSeed(2, "GERGER"),
            new DistrictSeed(2, "ÇELİKHAN"),
            new DistrictSeed(2, "BESNİ"),
            new DistrictSeed(2, "MERKEZ"),
            new DistrictSeed(3, "Afyon Havalimanı"),
            new DistrictSeed(3, "KIZILÖREN"),
            new DistrictSeed(3, "HOCALAR"),
            new DistrictSeed(3, "EVCİLER"),
            new DistrictSeed(3, "ÇOBANLAR"),
            new DistrictSeed(3, "İSCEHİSAR"),
            new DistrictSeed(3, "BAYAT"),
            new DistrictSeed(3, "BAŞMAKÇI"),
            new DistrictSeed(3, "ŞUHUT"),
            new DistrictSeed(3, "SULTANDAĞI"),
            new DistrictSeed(3, "SİNANPAŞA"),
            new DistrictSeed(3, "SANDIKLI"),
            new DistrictSeed(3, "İHSANİYE"),
            new DistrictSeed(3, "EMİRDAĞ"),
            new DistrictSeed(3, "DİNAR"),
            new DistrictSeed(3, "DAZKIRI"),
            new DistrictSeed(3, "ÇAY"),
            new DistrictSeed(3, "BOLVADİN"),
            new DistrictSeed(3, "MERKEZ"),
            new DistrictSeed(4, "Ağrı Ahmed-i Hani Havalimanı"),
            new DistrictSeed(4, "TUTAK"),
            new DistrictSeed(4, "TAŞLIÇAY"),
            new DistrictSeed(4, "PATNOS"),
            new DistrictSeed(4, "HAMUR"),
            new DistrictSeed(4, "ELEŞKİRT"),
            new DistrictSeed(4, "DOĞUBAYAZIT"),
            new DistrictSeed(4, "DİYADİN"),
            new DistrictSeed(4, "MERKEZ"),
            new DistrictSeed(5, "Amasya Merzifon Havalimanı"),
            new DistrictSeed(5, "HAMAMÖZÜ"),
            new DistrictSeed(5, "TAŞOVA"),
            new DistrictSeed(5, "SULUOVA"),
            new DistrictSeed(5, "MERZİFON"),
            new DistrictSeed(5, "GÜMÜŞHACIKÖY"),
            new DistrictSeed(5, "GÖYNÜCEK"),
            new DistrictSeed(5, "MERKEZ"),
            new DistrictSeed(6, "Ankara Esenboğa Havalimanı"),
            new DistrictSeed(6, "PURSAKLAR"),
            new DistrictSeed(6, "EVREN"),
            new DistrictSeed(6, "ETİMESGUT"),
            new DistrictSeed(6, "AKYURT"),
            new DistrictSeed(6, "KAHRAMANKAZAN"),
            new DistrictSeed(6, "SİNCAN"),
            new DistrictSeed(6, "MAMAK"),
            new DistrictSeed(6, "KEÇİÖREN"),
            new DistrictSeed(6, "GÖLBAŞI"),
            new DistrictSeed(6, "YENİMAHALLE"),
            new DistrictSeed(6, "ŞEREFLİKOÇHİSAR"),
            new DistrictSeed(6, "POLATLI"),
            new DistrictSeed(6, "NALLIHAN"),
            new DistrictSeed(6, "KIZILCAHAMAM"),
            new DistrictSeed(6, "KALECİK"),
            new DistrictSeed(6, "HAYMANA"),
            new DistrictSeed(6, "GÜDÜL"),
            new DistrictSeed(6, "ELMADAĞ"),
            new DistrictSeed(6, "ÇUBUK"),
            new DistrictSeed(6, "ÇANKAYA"),
            new DistrictSeed(6, "ÇAMLIDERE"),
            new DistrictSeed(6, "BEYPAZARI"),
            new DistrictSeed(6, "BALA"),
            new DistrictSeed(6, "AYAŞ"),
            new DistrictSeed(6, "ALTINDAĞ"),
            new DistrictSeed(7, "Gazipaşa Havalimanı"),
            new DistrictSeed(7, "Antalya Havalimanı"),
            new DistrictSeed(7, "MURATPAŞA"),
            new DistrictSeed(7, "KONYAALTI"),
            new DistrictSeed(7, "KEPEZ"),
            new DistrictSeed(7, "DÖŞEMEALTI"),
            new DistrictSeed(7, "AKSU"),
            new DistrictSeed(7, "KEMER"),
            new DistrictSeed(7, "İBRADI"),
            new DistrictSeed(7, "DEMRE"),
            new DistrictSeed(7, "SERİK"),
            new DistrictSeed(7, "MANAVGAT"),
            new DistrictSeed(7, "KUMLUCA"),
            new DistrictSeed(7, "KORKUTELİ"),
            new DistrictSeed(7, "KAŞ"),
            new DistrictSeed(7, "GÜNDOĞMUŞ"),
            new DistrictSeed(7, "GAZİPAŞA"),
            new DistrictSeed(7, "FİNİKE"),
            new DistrictSeed(7, "ELMALI"),
            new DistrictSeed(7, "MERKEZ"),
            new DistrictSeed(7, "ALANYA"),
            new DistrictSeed(7, "AKSEKİ"),
            new DistrictSeed(8, "KEMALPAŞA"),
            new DistrictSeed(8, "MURGUL"),
            new DistrictSeed(8, "YUSUFELİ"),
            new DistrictSeed(8, "ŞAVŞAT"),
            new DistrictSeed(8, "HOPA"),
            new DistrictSeed(8, "BORÇKA"),
            new DistrictSeed(8, "MERKEZ"),
            new DistrictSeed(8, "ARHAVİ"),
            new DistrictSeed(8, "ARDANUÇ"),
            new DistrictSeed(9, "EFELER"),
            new DistrictSeed(9, "DİDİM"),
            new DistrictSeed(9, "KÖŞK"),
            new DistrictSeed(9, "KARPUZLU"),
            new DistrictSeed(9, "İNCİRLİOVA"),
            new DistrictSeed(9, "BUHARKENT"),
            new DistrictSeed(9, "YENİPAZAR"),
            new DistrictSeed(9, "SULTANHİSAR"),
            new DistrictSeed(9, "SÖKE"),
            new DistrictSeed(9, "NAZİLLİ"),
            new DistrictSeed(9, "KUYUCAK"),
            new DistrictSeed(9, "KUŞADASI"),
            new DistrictSeed(9, "KOÇARLI"),
            new DistrictSeed(9, "KARACASU"),
            new DistrictSeed(9, "GERMENCİK"),
            new DistrictSeed(9, "ÇİNE"),
            new DistrictSeed(9, "BOZDOĞAN"),
            new DistrictSeed(9, "MERKEZ"),
            new DistrictSeed(10, "Balıkesir Merkez Havalimanı"),
            new DistrictSeed(10, "Balıkesir Koca Seyit Havalimanı"),
            new DistrictSeed(10, "KARESİ"),
            new DistrictSeed(10, "ALTIEYLÜL"),
            new DistrictSeed(10, "GÖMEÇ"),
            new DistrictSeed(10, "MARMARA"),
            new DistrictSeed(10, "SUSURLUK"),
            new DistrictSeed(10, "SINDIRGI"),
            new DistrictSeed(10, "SAVAŞTEPE"),
            new DistrictSeed(10, "MANYAS"),
            new DistrictSeed(10, "KEPSUT"),
            new DistrictSeed(10, "İVRİNDİ"),
            new DistrictSeed(10, "HAVRAN"),
            new DistrictSeed(10, "GÖNEN"),
            new DistrictSeed(10, "ERDEK"),
            new DistrictSeed(10, "EDREMİT"),
            new DistrictSeed(10, "DURSUNBEY"),
            new DistrictSeed(10, "BURHANİYE"),
            new DistrictSeed(10, "BİGADİÇ"),
            new DistrictSeed(10, "BANDIRMA"),
            new DistrictSeed(10, "BALYA"),
            new DistrictSeed(10, "MERKEZ"),
            new DistrictSeed(10, "AYVALIK"),
            new DistrictSeed(11, "İNHİSAR"),
            new DistrictSeed(11, "YENİPAZAR"),
            new DistrictSeed(11, "SÖĞÜT"),
            new DistrictSeed(11, "PAZARYERİ"),
            new DistrictSeed(11, "OSMANELİ"),
            new DistrictSeed(11, "GÖLPAZARI"),
            new DistrictSeed(11, "BOZÜYÜK"),
            new DistrictSeed(11, "MERKEZ"),
            new DistrictSeed(12, "Bingöl Havalimanı"),
            new DistrictSeed(12, "YEDİSU"),
            new DistrictSeed(12, "YAYLADERE"),
            new DistrictSeed(12, "ADAKLI"),
            new DistrictSeed(12, "SOLHAN"),
            new DistrictSeed(12, "KİĞI"),
            new DistrictSeed(12, "KARLIOVA"),
            new DistrictSeed(12, "GENÇ"),
            new DistrictSeed(12, "MERKEZ"),
            new DistrictSeed(13, "GÜROYMAK"),
            new DistrictSeed(13, "TATVAN"),
            new DistrictSeed(13, "MUTKİ"),
            new DistrictSeed(13, "HİZAN"),
            new DistrictSeed(13, "MERKEZ"),
            new DistrictSeed(13, "AHLAT"),
            new DistrictSeed(13, "ADİLCEVAZ"),
            new DistrictSeed(14, "YENİÇAĞA"),
            new DistrictSeed(14, "DÖRTDİVAN"),
            new DistrictSeed(14, "SEBEN"),
            new DistrictSeed(14, "MUDURNU"),
            new DistrictSeed(14, "MENGEN"),
            new DistrictSeed(14, "KIBRISCIK"),
            new DistrictSeed(14, "GÖYNÜK"),
            new DistrictSeed(14, "GEREDE"),
            new DistrictSeed(14, "MERKEZ"),
            new DistrictSeed(15, "ÇELTİKÇİ"),
            new DistrictSeed(15, "ÇAVDIR"),
            new DistrictSeed(15, "ALTINYAYLA"),
            new DistrictSeed(15, "KEMER"),
            new DistrictSeed(15, "KARAMANLI"),
            new DistrictSeed(15, "YEŞİLOVA"),
            new DistrictSeed(15, "TEFENNİ"),
            new DistrictSeed(15, "GÖLHİSAR"),
            new DistrictSeed(15, "MERKEZ"),
            new DistrictSeed(15, "BUCAK"),
            new DistrictSeed(15, "AĞLASUN"),
            new DistrictSeed(16, "Bursa Yenişehir Havalimanı"),
            new DistrictSeed(16, "KESTEL"),
            new DistrictSeed(16, "GÜRSU"),
            new DistrictSeed(16, "YILDIRIM"),
            new DistrictSeed(16, "OSMANGAZİ"),
            new DistrictSeed(16, "NİLÜFER"),
            new DistrictSeed(16, "HARMANCIK"),
            new DistrictSeed(16, "BÜYÜKORHAN"),
            new DistrictSeed(16, "YENİŞEHİR"),
            new DistrictSeed(16, "ORHANGAZİ"),
            new DistrictSeed(16, "ORHANELİ"),
            new DistrictSeed(16, "MUSTAFAKEMALPAŞA"),
            new DistrictSeed(16, "MUDANYA"),
            new DistrictSeed(16, "KELES"),
            new DistrictSeed(16, "KARACABEY"),
            new DistrictSeed(16, "İZNİK"),
            new DistrictSeed(16, "İNEGÖL"),
            new DistrictSeed(16, "GEMLİK"),
            new DistrictSeed(17, "Çanakkale Havalimanı"),
            new DistrictSeed(17, "Gökçeada Havalimanı"),
            new DistrictSeed(17, "YENİCE"),
            new DistrictSeed(17, "LAPSEKİ"),
            new DistrictSeed(17, "GÖKÇEADA"),
            new DistrictSeed(17, "GELİBOLU"),
            new DistrictSeed(17, "EZİNE"),
            new DistrictSeed(17, "ECEABAT"),
            new DistrictSeed(17, "MERKEZ"),
            new DistrictSeed(17, "ÇAN"),
            new DistrictSeed(17, "BOZCAADA"),
            new DistrictSeed(17, "BİGA"),
            new DistrictSeed(17, "BAYRAMİÇ"),
            new DistrictSeed(17, "AYVACIK"),
            new DistrictSeed(18, "KORGUN"),
            new DistrictSeed(18, "BAYRAMÖREN"),
            new DistrictSeed(18, "KIZILIRMAK"),
            new DistrictSeed(18, "ATKARACALAR"),
            new DistrictSeed(18, "YAPRAKLI"),
            new DistrictSeed(18, "ŞABANÖZÜ"),
            new DistrictSeed(18, "ORTA"),
            new DistrictSeed(18, "KURŞUNLU"),
            new DistrictSeed(18, "ILGAZ"),
            new DistrictSeed(18, "ELDİVAN"),
            new DistrictSeed(18, "ÇERKEŞ"),
            new DistrictSeed(18, "MERKEZ"),
            new DistrictSeed(19, "OĞUZLAR"),
            new DistrictSeed(19, "LAÇİN"),
            new DistrictSeed(19, "DODURGA"),
            new DistrictSeed(19, "UĞURLUDAĞ"),
            new DistrictSeed(19, "BOĞAZKALE"),
            new DistrictSeed(19, "SUNGURLU"),
            new DistrictSeed(19, "OSMANCIK"),
            new DistrictSeed(19, "ORTAKÖY"),
            new DistrictSeed(19, "MECİTÖZÜ"),
            new DistrictSeed(19, "KARGI"),
            new DistrictSeed(19, "İSKİLİP"),
            new DistrictSeed(19, "MERKEZ"),
            new DistrictSeed(19, "BAYAT"),
            new DistrictSeed(19, "ALACA"),
            new DistrictSeed(20, "Denizli Çardak Havalimanı"),
            new DistrictSeed(20, "MERKEZEFENDİ"),
            new DistrictSeed(20, "BOZKURT"),
            new DistrictSeed(20, "BEYAĞAÇ"),
            new DistrictSeed(20, "BAKLAN"),
            new DistrictSeed(20, "PAMUKKALE"),
            new DistrictSeed(20, "SERİNHİSAR"),
            new DistrictSeed(20, "HONAZ"),
            new DistrictSeed(20, "BEKİLLİ"),
            new DistrictSeed(20, "BABADAĞ"),
            new DistrictSeed(20, "TAVAS"),
            new DistrictSeed(20, "SARAYKÖY"),
            new DistrictSeed(20, "KALE"),
            new DistrictSeed(20, "GÜNEY"),
            new DistrictSeed(20, "MERKEZ"),
            new DistrictSeed(20, "ÇİVRİL"),
            new DistrictSeed(20, "ÇARDAK"),
            new DistrictSeed(20, "ÇAMELİ"),
            new DistrictSeed(20, "ÇAL"),
            new DistrictSeed(20, "BULDAN"),
            new DistrictSeed(20, "ACIPAYAM"),
            new DistrictSeed(21, "Diyarbakır Havalimanı"),
            new DistrictSeed(21, "YENİŞEHİR"),
            new DistrictSeed(21, "SUR"),
            new DistrictSeed(21, "KAYAPINAR"),
            new DistrictSeed(21, "BAĞLAR"),
            new DistrictSeed(21, "KOCAKÖY"),
            new DistrictSeed(21, "EĞİL"),
            new DistrictSeed(21, "SİLVAN"),
            new DistrictSeed(21, "LİCE"),
            new DistrictSeed(21, "KULP"),
            new DistrictSeed(21, "HAZRO"),
            new DistrictSeed(21, "HANİ"),
            new DistrictSeed(21, "ERGANİ"),
            new DistrictSeed(21, "MERKEZ"),
            new DistrictSeed(21, "DİCLE"),
            new DistrictSeed(21, "ÇÜNGÜŞ"),
            new DistrictSeed(21, "ÇINAR"),
            new DistrictSeed(21, "ÇERMİK"),
            new DistrictSeed(21, "BİSMİL"),
            new DistrictSeed(22, "SÜLOĞLU"),
            new DistrictSeed(22, "UZUNKÖPRÜ"),
            new DistrictSeed(22, "MERİÇ"),
            new DistrictSeed(22, "LALAPAŞA"),
            new DistrictSeed(22, "KEŞAN"),
            new DistrictSeed(22, "İPSALA"),
            new DistrictSeed(22, "HAVSA"),
            new DistrictSeed(22, "ENEZ"),
            new DistrictSeed(22, "MERKEZ"),
            new DistrictSeed(23, "Elazığ Havalimanı"),
            new DistrictSeed(23, "ALACAKAYA"),
            new DistrictSeed(23, "KOVANCILAR"),
            new DistrictSeed(23, "ARICAK"),
            new DistrictSeed(23, "SİVRİCE"),
            new DistrictSeed(23, "PALU"),
            new DistrictSeed(23, "MADEN"),
            new DistrictSeed(23, "KEBAN"),
            new DistrictSeed(23, "KARAKOÇAN"),
            new DistrictSeed(23, "MERKEZ"),
            new DistrictSeed(23, "BASKİL"),
            new DistrictSeed(23, "AĞIN"),
            new DistrictSeed(24, "Erzincan Havalimanı"),
            new DistrictSeed(24, "OTLUKBELİ"),
            new DistrictSeed(24, "ÜZÜMLÜ"),
            new DistrictSeed(24, "TERCAN"),
            new DistrictSeed(24, "REFAHİYE"),
            new DistrictSeed(24, "KEMALİYE"),
            new DistrictSeed(24, "KEMAH"),
            new DistrictSeed(24, "İLİÇ"),
            new DistrictSeed(24, "MERKEZ"),
            new DistrictSeed(24, "ÇAYIRLI"),
            new DistrictSeed(25, "Erzurum Havalimanı"),
            new DistrictSeed(25, "YAKUTİYE"),
            new DistrictSeed(25, "PALANDÖKEN"),
            new DistrictSeed(25, "KÖPRÜKÖY"),
            new DistrictSeed(25, "AZİZİYE"),
            new DistrictSeed(25, "PAZARYOLU"),
            new DistrictSeed(25, "UZUNDERE"),
            new DistrictSeed(25, "KARAÇOBAN"),
            new DistrictSeed(25, "TORTUM"),
            new DistrictSeed(25, "TEKMAN"),
            new DistrictSeed(25, "ŞENKAYA"),
            new DistrictSeed(25, "PASİNLER"),
            new DistrictSeed(25, "OLUR"),
            new DistrictSeed(25, "OLTU"),
            new DistrictSeed(25, "NARMAN"),
            new DistrictSeed(25, "KARAYAZI"),
            new DistrictSeed(25, "İSPİR"),
            new DistrictSeed(25, "HORASAN"),
            new DistrictSeed(25, "HINIS"),
            new DistrictSeed(25, "MERKEZ"),
            new DistrictSeed(25, "ÇAT"),
            new DistrictSeed(25, "AŞKALE"),
            new DistrictSeed(26, "Eskişehir Anadolu Havalimanı"),
            new DistrictSeed(26, "TEPEBAŞI"),
            new DistrictSeed(26, "ODUNPAZARI"),
            new DistrictSeed(26, "MİHALGAZİ"),
            new DistrictSeed(26, "HAN"),
            new DistrictSeed(26, "GÜNYÜZÜ"),
            new DistrictSeed(26, "İNÖNÜ"),
            new DistrictSeed(26, "BEYLİKOVA"),
            new DistrictSeed(26, "ALPU"),
            new DistrictSeed(26, "SİVRİHİSAR"),
            new DistrictSeed(26, "SEYİTGAZİ"),
            new DistrictSeed(26, "SARICAKAYA"),
            new DistrictSeed(26, "MİHALIÇÇIK"),
            new DistrictSeed(26, "MAHMUDİYE"),
            new DistrictSeed(26, "MERKEZ"),
            new DistrictSeed(26, "ÇİFTELER"),
            new DistrictSeed(27, "Gaziantep Havalimanı"),
            new DistrictSeed(27, "MERKEZ"),
            new DistrictSeed(27, "NURDAĞI"),
            new DistrictSeed(27, "KARKAMIŞ"),
            new DistrictSeed(27, "ŞEHİTKAMİL"),
            new DistrictSeed(27, "ŞAHİNBEY"),
            new DistrictSeed(27, "YAVUZELİ"),
            new DistrictSeed(27, "OĞUZELİ"),
            new DistrictSeed(27, "NİZİP"),
            new DistrictSeed(27, "İSLAHİYE"),
            new DistrictSeed(27, "ARABAN"),
            new DistrictSeed(28, "GÜCE"),
            new DistrictSeed(28, "DOĞANKENT"),
            new DistrictSeed(28, "ÇANAKÇI"),
            new DistrictSeed(28, "ÇAMOLUK"),
            new DistrictSeed(28, "YAĞLIDERE"),
            new DistrictSeed(28, "PİRAZİZ"),
            new DistrictSeed(28, "TİREBOLU"),
            new DistrictSeed(28, "ŞEBİNKARAHİSAR"),
            new DistrictSeed(28, "KEŞAP"),
            new DistrictSeed(28, "GÖRELE"),
            new DistrictSeed(28, "MERKEZ"),
            new DistrictSeed(28, "EYNESİL"),
            new DistrictSeed(28, "ESPİYE"),
            new DistrictSeed(28, "DERELİ"),
            new DistrictSeed(28, "BULANCAK"),
            new DistrictSeed(28, "ALUCRA"),
            new DistrictSeed(29, "KÜRTÜN"),
            new DistrictSeed(29, "KÖSE"),
            new DistrictSeed(29, "TORUL"),
            new DistrictSeed(29, "ŞİRAN"),
            new DistrictSeed(29, "KELKİT"),
            new DistrictSeed(29, "MERKEZ"),
            new DistrictSeed(30, "Hakkâri Yüksekova Selahaddin Eyyubi Havalimanı"),
            new DistrictSeed(30, "YÜKSEKOVA"),
            new DistrictSeed(30, "ŞEMDİNLİ"),
            new DistrictSeed(30, "MERKEZ"),
            new DistrictSeed(30, "ÇUKURCA"),
            new DistrictSeed(31, "Hatay Havalimanı"),
            new DistrictSeed(31, "PAYAS"),
            new DistrictSeed(31, "DEFNE"),
            new DistrictSeed(31, "ARSUZ"),
            new DistrictSeed(31, "ANTAKYA"),
            new DistrictSeed(31, "KUMLU"),
            new DistrictSeed(31, "BELEN"),
            new DistrictSeed(31, "ERZİN"),
            new DistrictSeed(31, "YAYLADAĞI"),
            new DistrictSeed(31, "SAMANDAĞ"),
            new DistrictSeed(31, "REYHANLI"),
            new DistrictSeed(31, "KIRIKHAN"),
            new DistrictSeed(31, "İSKENDERUN"),
            new DistrictSeed(31, "MERKEZ"),
            new DistrictSeed(31, "HASSA"),
            new DistrictSeed(31, "DÖRTYOL"),
            new DistrictSeed(31, "ALTINÖZÜ"),
            new DistrictSeed(32, "Isparta Süleyman Demirel Havalimanı"),
            new DistrictSeed(32, "YENİŞARBADEMLİ"),
            new DistrictSeed(32, "GÖNEN"),
            new DistrictSeed(32, "AKSU"),
            new DistrictSeed(32, "YALVAÇ"),
            new DistrictSeed(32, "ULUBORLU"),
            new DistrictSeed(32, "ŞARKİKARAAĞAÇ"),
            new DistrictSeed(32, "SÜTÇÜLER"),
            new DistrictSeed(32, "SENİRKENT"),
            new DistrictSeed(32, "KEÇİBORLU"),
            new DistrictSeed(32, "MERKEZ"),
            new DistrictSeed(32, "GELENDOST"),
            new DistrictSeed(32, "EĞİRDİR"),
            new DistrictSeed(32, "ATABEY"),
            new DistrictSeed(33, "YENİŞEHİR"),
            new DistrictSeed(33, "TOROSLAR"),
            new DistrictSeed(33, "MEZİTLİ"),
            new DistrictSeed(33, "AKDENİZ"),
            new DistrictSeed(33, "ÇAMLIYAYLA"),
            new DistrictSeed(33, "BOZYAZI"),
            new DistrictSeed(33, "AYDINCIK"),
            new DistrictSeed(33, "TARSUS"),
            new DistrictSeed(33, "SİLİFKE"),
            new DistrictSeed(33, "MUT"),
            new DistrictSeed(33, "MERKEZ"),
            new DistrictSeed(33, "GÜLNAR"),
            new DistrictSeed(33, "ERDEMLİ"),
            new DistrictSeed(33, "ANAMUR"),
            new DistrictSeed(34, "İstanbul Havalimanı"),
            new DistrictSeed(34, "Atatürk Havalimanı"),
            new DistrictSeed(34, "Sabiha Gökçen Havalimanı"),
            new DistrictSeed(34, "SULTANGAZİ"),
            new DistrictSeed(34, "SANCAKTEPE"),
            new DistrictSeed(34, "ESENYURT"),
            new DistrictSeed(34, "ÇEKMEKÖY"),
            new DistrictSeed(34, "BEYLİKDÜZÜ"),
            new DistrictSeed(34, "BAŞAKŞEHİR"),
            new DistrictSeed(34, "ATAŞEHİR"),
            new DistrictSeed(34, "ARNAVUTKÖY"),
            new DistrictSeed(34, "ESENLER"),
            new DistrictSeed(34, "TUZLA"),
            new DistrictSeed(34, "SULTANBEYLİ"),
            new DistrictSeed(34, "MALTEPE"),
            new DistrictSeed(34, "GÜNGÖREN"),
            new DistrictSeed(34, "BAHÇELİEVLER"),
            new DistrictSeed(34, "BAĞCILAR"),
            new DistrictSeed(34, "AVCILAR"),
            new DistrictSeed(34, "BAYRAMPAŞA"),
            new DistrictSeed(34, "ÜMRANİYE"),
            new DistrictSeed(34, "PENDİK"),
            new DistrictSeed(34, "KÜÇÜKÇEKMECE"),
            new DistrictSeed(34, "KAĞITHANE"),
            new DistrictSeed(34, "BÜYÜKÇEKMECE"),
            new DistrictSeed(34, "ZEYTİNBURNU"),
            new DistrictSeed(34, "ÜSKÜDAR"),
            new DistrictSeed(34, "ŞİŞLİ"),
            new DistrictSeed(34, "ŞİLE"),
            new DistrictSeed(34, "SİLİVRİ"),
            new DistrictSeed(34, "SARIYER"),
            new DistrictSeed(34, "KARTAL"),
            new DistrictSeed(34, "KADIKÖY"),
            new DistrictSeed(34, "GAZİOSMANPAŞA"),
            new DistrictSeed(34, "FATİH"),
            new DistrictSeed(34, "EYÜPSULTAN"),
            new DistrictSeed(34, "EMİNÖNÜ"),
            new DistrictSeed(34, "ÇATALCA"),
            new DistrictSeed(34, "BEYOĞLU"),
            new DistrictSeed(34, "BEYKOZ"),
            new DistrictSeed(34, "BEŞİKTAŞ"),
            new DistrictSeed(34, "BAKIRKÖY"),
            new DistrictSeed(34, "ADALAR"),
            new DistrictSeed(35, "Adnan Menderes Havalimanı"),
            new DistrictSeed(35, "KARABAĞLAR"),
            new DistrictSeed(35, "BAYRAKLI"),
            new DistrictSeed(35, "GÜZELBAHÇE"),
            new DistrictSeed(35, "NARLIDERE"),
            new DistrictSeed(35, "GAZİEMİR"),
            new DistrictSeed(35, "ÇİĞLİ"),
            new DistrictSeed(35, "BALÇOVA"),
            new DistrictSeed(35, "MENDERES"),
            new DistrictSeed(35, "KONAK"),
            new DistrictSeed(35, "BUCA"),
            new DistrictSeed(35, "BEYDAĞ"),
            new DistrictSeed(35, "URLA"),
            new DistrictSeed(35, "TORBALI"),
            new DistrictSeed(35, "TİRE"),
            new DistrictSeed(35, "SELÇUK"),
            new DistrictSeed(35, "SEFERİHİSAR"),
            new DistrictSeed(35, "ÖDEMİŞ"),
            new DistrictSeed(35, "MENEMEN"),
            new DistrictSeed(35, "KİRAZ"),
            new DistrictSeed(35, "KINIK"),
            new DistrictSeed(35, "KEMALPAŞA"),
            new DistrictSeed(35, "KARŞIYAKA"),
            new DistrictSeed(35, "KARABURUN"),
            new DistrictSeed(35, "FOÇA"),
            new DistrictSeed(35, "DİKİLİ"),
            new DistrictSeed(35, "ÇEŞME"),
            new DistrictSeed(35, "BORNOVA"),
            new DistrictSeed(35, "BERGAMA"),
            new DistrictSeed(35, "BAYINDIR"),
            new DistrictSeed(35, "ALİAĞA"),
            new DistrictSeed(36, "Kars Harakani Havalimanı"),
            new DistrictSeed(36, "AKYAKA"),
            new DistrictSeed(36, "SUSUZ"),
            new DistrictSeed(36, "SELİM"),
            new DistrictSeed(36, "SARIKAMIŞ"),
            new DistrictSeed(36, "MERKEZ"),
            new DistrictSeed(36, "KAĞIZMAN"),
            new DistrictSeed(36, "DİGOR"),
            new DistrictSeed(36, "ARPAÇAY"),
            new DistrictSeed(37, "Kastamonu Havalimanı"),
            new DistrictSeed(37, "SEYDİLER"),
            new DistrictSeed(37, "HANÖNÜ"),
            new DistrictSeed(37, "DOĞANYURT"),
            new DistrictSeed(37, "AĞLI"),
            new DistrictSeed(37, "ŞENPAZAR"),
            new DistrictSeed(37, "PINARBAŞI"),
            new DistrictSeed(37, "İHSANGAZİ"),
            new DistrictSeed(37, "TOSYA"),
            new DistrictSeed(37, "TAŞKÖPRÜ"),
            new DistrictSeed(37, "KÜRE"),
            new DistrictSeed(37, "MERKEZ"),
            new DistrictSeed(37, "İNEBOLU"),
            new DistrictSeed(37, "DEVREKANİ"),
            new DistrictSeed(37, "DADAY"),
            new DistrictSeed(37, "ÇATALZEYTİN"),
            new DistrictSeed(37, "CİDE"),
            new DistrictSeed(37, "BOZKURT"),
            new DistrictSeed(37, "AZDAVAY"),
            new DistrictSeed(37, "ARAÇ"),
            new DistrictSeed(37, "ABANA"),
            new DistrictSeed(38, "Erkilet Havalimanı"),
            new DistrictSeed(38, "ÖZVATAN"),
            new DistrictSeed(38, "HACILAR"),
            new DistrictSeed(38, "MELİKGAZİ"),
            new DistrictSeed(38, "KOCASİNAN"),
            new DistrictSeed(38, "TALAS"),
            new DistrictSeed(38, "AKKIŞLA"),
            new DistrictSeed(38, "YEŞİLHİSAR"),
            new DistrictSeed(38, "YAHYALI"),
            new DistrictSeed(38, "TOMARZA"),
            new DistrictSeed(38, "SARIZ"),
            new DistrictSeed(38, "SARIOĞLAN"),
            new DistrictSeed(38, "PINARBAŞI"),
            new DistrictSeed(38, "İNCESU"),
            new DistrictSeed(38, "FELAHİYE"),
            new DistrictSeed(38, "DEVELİ"),
            new DistrictSeed(38, "BÜNYAN"),
            new DistrictSeed(39, "VİZE"),
            new DistrictSeed(39, "PINARHİSAR"),
            new DistrictSeed(39, "PEHLİVANKÖY"),
            new DistrictSeed(39, "LÜLEBURGAZ"),
            new DistrictSeed(39, "KOFÇAZ"),
            new DistrictSeed(39, "MERKEZ"),
            new DistrictSeed(39, "DEMİRKÖY"),
            new DistrictSeed(39, "BABAESKİ"),
            new DistrictSeed(40, "BOZTEPE"),
            new DistrictSeed(40, "AKÇAKENT"),
            new DistrictSeed(40, "AKPINAR"),
            new DistrictSeed(40, "MUCUR"),
            new DistrictSeed(40, "MERKEZ"),
            new DistrictSeed(40, "KAMAN"),
            new DistrictSeed(40, "ÇİÇEKDAĞI"),
            new DistrictSeed(41, "Cengiz Topel Havalimanı"),
            new DistrictSeed(41, "KARTEPE"),
            new DistrictSeed(41, "İZMİT"),
            new DistrictSeed(41, "DİLOVASI"),
            new DistrictSeed(41, "DARICA"),
            new DistrictSeed(41, "ÇAYIROVA"),
            new DistrictSeed(41, "BAŞİSKELE"),
            new DistrictSeed(41, "DERİNCE"),
            new DistrictSeed(41, "KÖRFEZ"),
            new DistrictSeed(41, "MERKEZ"),
            new DistrictSeed(41, "KARAMÜRSEL"),
            new DistrictSeed(41, "KANDIRA"),
            new DistrictSeed(41, "GÖLCÜK"),
            new DistrictSeed(41, "GEBZE"),
            new DistrictSeed(42, "Konya Havalimanı"),
            new DistrictSeed(42, "YALIHÜYÜK"),
            new DistrictSeed(42, "TUZLUKÇU"),
            new DistrictSeed(42, "HALKAPINAR"),
            new DistrictSeed(42, "GÜNEYSINIR"),
            new DistrictSeed(42, "EMİRGAZİ"),
            new DistrictSeed(42, "DERBENT"),
            new DistrictSeed(42, "ÇELTİK"),
            new DistrictSeed(42, "AHIRLI"),
            new DistrictSeed(42, "TAŞKENT"),
            new DistrictSeed(42, "SELÇUKLU"),
            new DistrictSeed(42, "MERAM"),
            new DistrictSeed(42, "KARATAY"),
            new DistrictSeed(42, "HÜYÜK"),
            new DistrictSeed(42, "DEREBUCAK"),
            new DistrictSeed(42, "ALTINEKİN"),
            new DistrictSeed(42, "AKÖREN"),
            new DistrictSeed(42, "YUNAK"),
            new DistrictSeed(42, "SEYDİŞEHİR"),
            new DistrictSeed(42, "SARAYÖNÜ"),
            new DistrictSeed(42, "KULU"),
            new DistrictSeed(42, "KARAPINAR"),
            new DistrictSeed(42, "KADINHANI"),
            new DistrictSeed(42, "ILGIN"),
            new DistrictSeed(42, "HADİM"),
            new DistrictSeed(42, "EREĞLİ"),
            new DistrictSeed(42, "DOĞANHİSAR"),
            new DistrictSeed(42, "ÇUMRA"),
            new DistrictSeed(42, "CİHANBEYLİ"),
            new DistrictSeed(42, "BOZKIR"),
            new DistrictSeed(42, "BEYŞEHİR"),
            new DistrictSeed(42, "AKŞEHİR"),
            new DistrictSeed(43, "Zafer Havalimanı"),
            new DistrictSeed(43, "PAZARLAR"),
            new DistrictSeed(43, "ÇAVDARHİSAR"),
            new DistrictSeed(43, "ŞAPHANE"),
            new DistrictSeed(43, "HİSARCIK"),
            new DistrictSeed(43, "DUMLUPINAR"),
            new DistrictSeed(43, "ASLANAPA"),
            new DistrictSeed(43, "TAVŞANLI"),
            new DistrictSeed(43, "SİMAV"),
            new DistrictSeed(43, "MERKEZ"),
            new DistrictSeed(43, "GEDİZ"),
            new DistrictSeed(43, "EMET"),
            new DistrictSeed(43, "DOMANİÇ"),
            new DistrictSeed(43, "ALTINTAŞ"),
            new DistrictSeed(44, "Erhaç Havalimanı"),
            new DistrictSeed(44, "YAZIHAN"),
            new DistrictSeed(44, "KULUNCAK"),
            new DistrictSeed(44, "KALE"),
            new DistrictSeed(44, "DOĞANYOL"),
            new DistrictSeed(44, "BATTALGAZİ"),
            new DistrictSeed(44, "YEŞİLYURT"),
            new DistrictSeed(44, "PÜTÜRGE"),
            new DistrictSeed(44, "MERKEZ"),
            new DistrictSeed(44, "HEKİMHAN"),
            new DistrictSeed(44, "DOĞANŞEHİR"),
            new DistrictSeed(44, "DARENDE"),
            new DistrictSeed(44, "ARGUVAN"),
            new DistrictSeed(44, "ARAPGİR"),
            new DistrictSeed(44, "AKÇADAĞ"),
            new DistrictSeed(45, "YUNUSEMRE"),
            new DistrictSeed(45, "ŞEHZADELER"),
            new DistrictSeed(45, "KÖPRÜBAŞI"),
            new DistrictSeed(45, "GÖLMARMARA"),
            new DistrictSeed(45, "AHMETLİ"),
            new DistrictSeed(45, "TURGUTLU"),
            new DistrictSeed(45, "SOMA"),
            new DistrictSeed(45, "SELENDİ"),
            new DistrictSeed(45, "SARUHANLI"),
            new DistrictSeed(45, "SARIGÖL"),
            new DistrictSeed(45, "SALİHLİ"),
            new DistrictSeed(45, "MERKEZ"),
            new DistrictSeed(45, "KULA"),
            new DistrictSeed(45, "KIRKAĞAÇ"),
            new DistrictSeed(45, "GÖRDES"),
            new DistrictSeed(45, "DEMİRCİ"),
            new DistrictSeed(45, "ALAŞEHİR"),
            new DistrictSeed(45, "AKHİSAR"),
            new DistrictSeed(46, "Kahramanmaraş Havalimanı"),
            new DistrictSeed(46, "ONİKİŞUBAT"),
            new DistrictSeed(46, "DULKADİROĞLU"),
            new DistrictSeed(46, "NURHAK"),
            new DistrictSeed(46, "EKİNÖZÜ"),
            new DistrictSeed(46, "ÇAĞLAYANCERİT"),
            new DistrictSeed(46, "TÜRKOĞLU"),
            new DistrictSeed(46, "PAZARCIK"),
            new DistrictSeed(46, "MERKEZ"),
            new DistrictSeed(46, "GÖKSUN"),
            new DistrictSeed(46, "ELBİSTAN"),
            new DistrictSeed(46, "ANDIRIN"),
            new DistrictSeed(46, "AFŞİN"),
            new DistrictSeed(47, "Mardin Havalimanı"),
            new DistrictSeed(47, "ARTUKLU"),
            new DistrictSeed(47, "YEŞİLLİ"),
            new DistrictSeed(47, "DARGEÇİT"),
            new DistrictSeed(47, "SAVUR"),
            new DistrictSeed(47, "ÖMERLİ"),
            new DistrictSeed(47, "NUSAYBİN"),
            new DistrictSeed(47, "MİDYAT"),
            new DistrictSeed(47, "MAZIDAĞI"),
            new DistrictSeed(47, "MERKEZ"),
            new DistrictSeed(47, "KIZILTEPE"),
            new DistrictSeed(47, "DERİK"),
            new DistrictSeed(48, "Milas-Bodrum Havalimanı"),
            new DistrictSeed(48, "Dalaman Havalimanı"),
            new DistrictSeed(48, "SEYDİKEMER"),
            new DistrictSeed(48, "MENTEŞE"),
            new DistrictSeed(48, "KAVAKLIDERE"),
            new DistrictSeed(48, "ORTACA"),
            new DistrictSeed(48, "DALAMAN"),
            new DistrictSeed(48, "YATAĞAN"),
            new DistrictSeed(48, "ULA"),
            new DistrictSeed(48, "MERKEZ"),
            new DistrictSeed(48, "MİLAS"),
            new DistrictSeed(48, "MARMARİS"),
            new DistrictSeed(48, "KÖYCEĞİZ"),
            new DistrictSeed(48, "FETHİYE"),
            new DistrictSeed(48, "DATÇA"),
            new DistrictSeed(48, "BODRUM"),
            new DistrictSeed(49, "Muş Havalimanı"),
            new DistrictSeed(49, "KORKUT"),
            new DistrictSeed(49, "HASKÖY"),
            new DistrictSeed(49, "VARTO"),
            new DistrictSeed(49, "MERKEZ"),
            new DistrictSeed(49, "MALAZGİRT"),
            new DistrictSeed(49, "BULANIK"),
            new DistrictSeed(50, "Nevşehir Kapadokya Havalimanı"),
            new DistrictSeed(50, "ACIGÖL"),
            new DistrictSeed(50, "ÜRGÜP"),
            new DistrictSeed(50, "MERKEZ"),
            new DistrictSeed(50, "KOZAKLI"),
            new DistrictSeed(50, "HACIBEKTAŞ"),
            new DistrictSeed(50, "GÜLŞEHİR"),
            new DistrictSeed(50, "DERİNKUYU"),
            new DistrictSeed(50, "AVANOS"),
            new DistrictSeed(51, "ÇİFTLİK"),
            new DistrictSeed(51, "ALTUNHİSAR"),
            new DistrictSeed(51, "ULUKIŞLA"),
            new DistrictSeed(51, "MERKEZ"),
            new DistrictSeed(51, "ÇAMARDI"),
            new DistrictSeed(51, "BOR"),
            new DistrictSeed(52, "Ordu-Giresun Havalimanı"),
            new DistrictSeed(52, "ALTINORDU"),
            new DistrictSeed(52, "KABATAŞ"),
            new DistrictSeed(52, "KABADÜZ"),
            new DistrictSeed(52, "İKİZCE"),
            new DistrictSeed(52, "ÇAYBAŞI"),
            new DistrictSeed(52, "ÇATALPINAR"),
            new DistrictSeed(52, "ÇAMAŞ"),
            new DistrictSeed(52, "GÜRGENTEPE"),
            new DistrictSeed(52, "GÜLYALI"),
            new DistrictSeed(52, "ÜNYE"),
            new DistrictSeed(52, "ULUBEY"),
            new DistrictSeed(52, "PERŞEMBE"),
            new DistrictSeed(52, "MERKEZ"),
            new DistrictSeed(52, "MESUDİYE"),
            new DistrictSeed(52, "KUMRU"),
            new DistrictSeed(52, "KORGAN"),
            new DistrictSeed(52, "GÖLKÖY"),
            new DistrictSeed(52, "FATSA"),
            new DistrictSeed(52, "AYBASTI"),
            new DistrictSeed(52, "AKKUŞ"),
            new DistrictSeed(53, "İYİDERE"),
            new DistrictSeed(53, "HEMŞİN"),
            new DistrictSeed(53, "DEREPAZARI"),
            new DistrictSeed(53, "GÜNEYSU"),
            new DistrictSeed(53, "MERKEZ"),
            new DistrictSeed(53, "PAZAR"),
            new DistrictSeed(53, "KALKANDERE"),
            new DistrictSeed(53, "İKİZDERE"),
            new DistrictSeed(53, "FINDIKLI"),
            new DistrictSeed(53, "ÇAYELİ"),
            new DistrictSeed(53, "ÇAMLIHEMŞİN"),
            new DistrictSeed(53, "ARDEŞEN"),
            new DistrictSeed(54, "SERDİVAN"),
            new DistrictSeed(54, "ERENLER"),
            new DistrictSeed(54, "ARİFİYE"),
            new DistrictSeed(54, "ADAPAZARI"),
            new DistrictSeed(54, "SÖĞÜTLÜ"),
            new DistrictSeed(54, "KARAPÜRÇEK"),
            new DistrictSeed(54, "FERİZLİ"),
            new DistrictSeed(54, "TARAKLI"),
            new DistrictSeed(54, "PAMUKOVA"),
            new DistrictSeed(54, "KOCAALİ"),
            new DistrictSeed(54, "SAPANCA"),
            new DistrictSeed(54, "MERKEZ"),
            new DistrictSeed(54, "KAYNARCA"),
            new DistrictSeed(54, "KARASU"),
            new DistrictSeed(54, "HENDEK"),
            new DistrictSeed(54, "GEYVE"),
            new DistrictSeed(54, "AKYAZI"),
            new DistrictSeed(55, "Samsun Çarşamba Havalimanı"),
            new DistrictSeed(55, "İLKADIM"),
            new DistrictSeed(55, "CANİK"),
            new DistrictSeed(55, "ATAKUM"),
            new DistrictSeed(55, "YAKAKENT"),
            new DistrictSeed(55, "AYVACIK"),
            new DistrictSeed(55, "TEKKEKÖY"),
            new DistrictSeed(55, "SALIPAZARI"),
            new DistrictSeed(55, "19 MAYIS"),
            new DistrictSeed(55, "ASARCIK"),
            new DistrictSeed(55, "VEZİRKÖPRÜ"),
            new DistrictSeed(55, "TERME"),
            new DistrictSeed(55, "MERKEZ"),
            new DistrictSeed(55, "LADİK"),
            new DistrictSeed(55, "KAVAK"),
            new DistrictSeed(55, "HAVZA"),
            new DistrictSeed(55, "ÇARŞAMBA"),
            new DistrictSeed(55, "BAFRA"),
            new DistrictSeed(55, "ALAÇAM"),
            new DistrictSeed(56, "Siirt Havalimanı"),
            new DistrictSeed(56, "TİLLO"),
            new DistrictSeed(56, "ŞİRVAN"),
            new DistrictSeed(56, "MERKEZ"),
            new DistrictSeed(56, "PERVARİ"),
            new DistrictSeed(56, "KURTALAN"),
            new DistrictSeed(56, "ERUH"),
            new DistrictSeed(56, "BAYKAN"),
            new DistrictSeed(57, "Sinop Havalimanı"),
            new DistrictSeed(57, "SARAYDÜZÜ"),
            new DistrictSeed(57, "DİKMEN"),
            new DistrictSeed(57, "TÜRKELİ"),
            new DistrictSeed(57, "MERKEZ"),
            new DistrictSeed(57, "GERZE"),
            new DistrictSeed(57, "ERFELEK"),
            new DistrictSeed(57, "DURAĞAN"),
            new DistrictSeed(57, "BOYABAT"),
            new DistrictSeed(57, "AYANCIK"),
            new DistrictSeed(58, "Sivas Nuri Demirağ Havalimanı"),
            new DistrictSeed(58, "ULAŞ"),
            new DistrictSeed(58, "GÖLOVA"),
            new DistrictSeed(58, "DOĞANŞAR"),
            new DistrictSeed(58, "ALTINYAYLA"),
            new DistrictSeed(58, "AKINCILAR"),
            new DistrictSeed(58, "ZARA"),
            new DistrictSeed(58, "YILDIZELİ"),
            new DistrictSeed(58, "ŞARKIŞLA"),
            new DistrictSeed(58, "SUŞEHRİ"),
            new DistrictSeed(58, "MERKEZ"),
            new DistrictSeed(58, "KOYULHİSAR"),
            new DistrictSeed(58, "KANGAL"),
            new DistrictSeed(58, "İMRANLI"),
            new DistrictSeed(58, "HAFİK"),
            new DistrictSeed(58, "GÜRÜN"),
            new DistrictSeed(58, "GEMEREK"),
            new DistrictSeed(58, "DİVRİĞİ"),
            new DistrictSeed(59, "Tekirdağ Çorlu Havalimanı"),
            new DistrictSeed(59, "SÜLEYMANPAŞA"),
            new DistrictSeed(59, "KAPAKLI"),
            new DistrictSeed(59, "ERGENE"),
            new DistrictSeed(59, "MARMARAEREĞLİSİ"),
            new DistrictSeed(59, "MERKEZ"),
            new DistrictSeed(59, "ŞARKÖY"),
            new DistrictSeed(59, "SARAY"),
            new DistrictSeed(59, "MURATLI"),
            new DistrictSeed(59, "MALKARA"),
            new DistrictSeed(59, "HAYRABOLU"),
            new DistrictSeed(59, "ÇORLU"),
            new DistrictSeed(59, "ÇERKEZKÖY"),
            new DistrictSeed(60, "Tokat Havalimanı"),
            new DistrictSeed(60, "SULUSARAY"),
            new DistrictSeed(60, "BAŞÇİFTLİK"),
            new DistrictSeed(60, "YEŞİLYURT"),
            new DistrictSeed(60, "PAZAR"),
            new DistrictSeed(60, "ZİLE"),
            new DistrictSeed(60, "TURHAL"),
            new DistrictSeed(60, "MERKEZ"),
            new DistrictSeed(60, "REŞADİYE"),
            new DistrictSeed(60, "NİKSAR"),
            new DistrictSeed(60, "ERBAA"),
            new DistrictSeed(60, "ARTOVA"),
            new DistrictSeed(60, "ALMUS"),
            new DistrictSeed(61, "Trabzon Havalimanı"),
            new DistrictSeed(61, "ORTAHİSAR"),
            new DistrictSeed(61, "KÖPRÜBAŞI"),
            new DistrictSeed(61, "HAYRAT"),
            new DistrictSeed(61, "DÜZKÖY"),
            new DistrictSeed(61, "DERNEKPAZARI"),
            new DistrictSeed(61, "ÇARŞIBAŞI"),
            new DistrictSeed(61, "ŞALPAZARI"),
            new DistrictSeed(61, "BEŞİKDÜZÜ"),
            new DistrictSeed(61, "YOMRA"),
            new DistrictSeed(61, "VAKFIKEBİR"),
            new DistrictSeed(61, "MERKEZ"),
            new DistrictSeed(61, "TONYA"),
            new DistrictSeed(61, "SÜRMENE"),
            new DistrictSeed(61, "OF"),
            new DistrictSeed(61, "MAÇKA"),
            new DistrictSeed(61, "ÇAYKARA"),
            new DistrictSeed(61, "ARSİN"),
            new DistrictSeed(61, "ARAKLI"),
            new DistrictSeed(61, "AKÇAABAT"),
            new DistrictSeed(62, "MERKEZ"),
            new DistrictSeed(62, "PÜLÜMÜR"),
            new DistrictSeed(62, "PERTEK"),
            new DistrictSeed(62, "OVACIK"),
            new DistrictSeed(62, "NAZIMİYE"),
            new DistrictSeed(62, "MAZGİRT"),
            new DistrictSeed(62, "HOZAT"),
            new DistrictSeed(62, "ÇEMİŞGEZEK"),
            new DistrictSeed(63, "Şanlıurfa GAP Havalimanı"),
            new DistrictSeed(63, "KARAKÖPRÜ"),
            new DistrictSeed(63, "HALİLİYE"),
            new DistrictSeed(63, "EYYÜBİYE"),
            new DistrictSeed(63, "HARRAN"),
            new DistrictSeed(63, "VİRANŞEHİR"),
            new DistrictSeed(63, "MERKEZ"),
            new DistrictSeed(63, "SURUÇ"),
            new DistrictSeed(63, "SİVEREK"),
            new DistrictSeed(63, "HİLVAN"),
            new DistrictSeed(63, "HALFETİ"),
            new DistrictSeed(63, "CEYLANPINAR"),
            new DistrictSeed(63, "BOZOVA"),
            new DistrictSeed(63, "BİRECİK"),
            new DistrictSeed(63, "AKÇAKALE"),
            new DistrictSeed(64, "Uşak Havalimanı"),
            new DistrictSeed(64, "MERKEZ"),
            new DistrictSeed(64, "ULUBEY"),
            new DistrictSeed(64, "SİVASLI"),
            new DistrictSeed(64, "KARAHALLI"),
            new DistrictSeed(64, "EŞME"),
            new DistrictSeed(64, "BANAZ"),
            new DistrictSeed(65, "Ferit Melen Havalimanı"),
            new DistrictSeed(65, "TUŞBA"),
            new DistrictSeed(65, "İPEKYOLU"),
            new DistrictSeed(65, "SARAY"),
            new DistrictSeed(65, "EDREMİT"),
            new DistrictSeed(65, "ÇALDIRAN"),
            new DistrictSeed(65, "BAHÇESARAY"),
            new DistrictSeed(65, "MERKEZ"),
            new DistrictSeed(65, "ÖZALP"),
            new DistrictSeed(65, "MURADİYE"),
            new DistrictSeed(65, "GÜRPINAR"),
            new DistrictSeed(65, "GEVAŞ"),
            new DistrictSeed(65, "ERCİŞ"),
            new DistrictSeed(65, "ÇATAK"),
            new DistrictSeed(65, "BAŞKALE"),
            new DistrictSeed(66, "YENİFAKILI"),
            new DistrictSeed(66, "SARAYKENT"),
            new DistrictSeed(66, "KADIŞEHRİ"),
            new DistrictSeed(66, "ÇANDIR"),
            new DistrictSeed(66, "AYDINCIK"),
            new DistrictSeed(66, "MERKEZ"),
            new DistrictSeed(66, "YERKÖY"),
            new DistrictSeed(66, "ŞEFAATLİ"),
            new DistrictSeed(66, "SORGUN"),
            new DistrictSeed(66, "SARIKAYA"),
            new DistrictSeed(66, "ÇEKEREK"),
            new DistrictSeed(66, "ÇAYIRALAN"),
            new DistrictSeed(66, "BOĞAZLIYAN"),
            new DistrictSeed(66, "AKDAĞMADENİ"),
            new DistrictSeed(67, "Zonguldak Havalimanı"),
            new DistrictSeed(67, "KOZLU"),
            new DistrictSeed(67, "KİLİMLİ"),
            new DistrictSeed(67, "GÖKÇEBEY"),
            new DistrictSeed(67, "ALAPLI"),
            new DistrictSeed(67, "MERKEZ"),
            new DistrictSeed(67, "EREĞLİ"),
            new DistrictSeed(67, "DEVREK"),
            new DistrictSeed(67, "ÇAYCUMA"),
            new DistrictSeed(68, "SULTANHANI"),
            new DistrictSeed(68, "GÜLAĞAÇ"),
            new DistrictSeed(68, "ESKİL"),
            new DistrictSeed(68, "SARIYAHŞİ"),
            new DistrictSeed(68, "GÜZELYURT"),
            new DistrictSeed(68, "AĞAÇÖREN"),
            new DistrictSeed(68, "ORTAKÖY"),
            new DistrictSeed(68, "MERKEZ"),
            new DistrictSeed(69, "DEMİRÖZÜ"),
            new DistrictSeed(69, "AYDINTEPE"),
            new DistrictSeed(69, "MERKEZ"),
            new DistrictSeed(70, "SARIVELİLER"),
            new DistrictSeed(70, "BAŞYAYLA"),
            new DistrictSeed(70, "KAZIMKARABEKİR"),
            new DistrictSeed(70, "AYRANCI"),
            new DistrictSeed(70, "MERKEZ"),
            new DistrictSeed(70, "ERMENEK"),
            new DistrictSeed(71, "YAHŞİHAN"),
            new DistrictSeed(71, "KARAKEÇİLİ"),
            new DistrictSeed(71, "ÇELEBİ"),
            new DistrictSeed(71, "BALIŞEYH"),
            new DistrictSeed(71, "BAHŞİLİ"),
            new DistrictSeed(71, "SULAKYURT"),
            new DistrictSeed(71, "MERKEZ"),
            new DistrictSeed(71, "KESKİN"),
            new DistrictSeed(71, "DELİCE"),
            new DistrictSeed(72, "Batman Havalimanı"),
            new DistrictSeed(72, "HASANKEYF"),
            new DistrictSeed(72, "SASON"),
            new DistrictSeed(72, "KOZLUK"),
            new DistrictSeed(72, "GERCÜŞ"),
            new DistrictSeed(72, "BEŞİRİ"),
            new DistrictSeed(72, "MERKEZ"),
            new DistrictSeed(73, "Şırnak Şerafettin Elçi Havalimanı"),
            new DistrictSeed(73, "GÜÇLÜKONAK"),
            new DistrictSeed(73, "ULUDERE"),
            new DistrictSeed(73, "MERKEZ"),
            new DistrictSeed(73, "SİLOPİ"),
            new DistrictSeed(73, "İDİL"),
            new DistrictSeed(73, "CİZRE"),
            new DistrictSeed(73, "BEYTÜŞŞEBAP"),
            new DistrictSeed(74, "AMASRA"),
            new DistrictSeed(74, "ULUS"),
            new DistrictSeed(74, "KURUCAŞİLE"),
            new DistrictSeed(74, "MERKEZ"),
            new DistrictSeed(75, "DAMAL"),
            new DistrictSeed(75, "POSOF"),
            new DistrictSeed(75, "HANAK"),
            new DistrictSeed(75, "GÖLE"),
            new DistrictSeed(75, "ÇILDIR"),
            new DistrictSeed(75, "MERKEZ"),
            new DistrictSeed(76, "Iğdır Havalimanı"),
            new DistrictSeed(76, "KARAKOYUNLU"),
            new DistrictSeed(76, "TUZLUCA"),
            new DistrictSeed(76, "MERKEZ"),
            new DistrictSeed(76, "ARALIK"),
            new DistrictSeed(77, "TERMAL"),
            new DistrictSeed(77, "ÇİFTLİKKÖY"),
            new DistrictSeed(77, "ÇINARCIK"),
            new DistrictSeed(77, "ARMUTLU"),
            new DistrictSeed(77, "ALTINOVA"),
            new DistrictSeed(77, "MERKEZ"),
            new DistrictSeed(78, "YENİCE"),
            new DistrictSeed(78, "SAFRANBOLU"),
            new DistrictSeed(78, "OVACIK"),
            new DistrictSeed(78, "MERKEZ"),
            new DistrictSeed(78, "ESKİPAZAR"),
            new DistrictSeed(78, "EFLANİ"),
            new DistrictSeed(79, "POLATELİ"),
            new DistrictSeed(79, "MUSABEYLİ"),
            new DistrictSeed(79, "ELBEYLİ"),
            new DistrictSeed(79, "MERKEZ"),
            new DistrictSeed(80, "TOPRAKKALE"),
            new DistrictSeed(80, "SUMBAS"),
            new DistrictSeed(80, "HASANBEYLİ"),
            new DistrictSeed(80, "DÜZİÇİ"),
            new DistrictSeed(80, "MERKEZ"),
            new DistrictSeed(80, "KADİRLİ"),
            new DistrictSeed(80, "BAHÇE"),
            new DistrictSeed(81, "KAYNAŞLI"),
            new DistrictSeed(81, "GÜMÜŞOVA"),
            new DistrictSeed(81, "ÇİLİMLİ"),
            new DistrictSeed(81, "GÖLYAKA"),
            new DistrictSeed(81, "CUMAYERİ"),
            new DistrictSeed(81, "YIĞILCA"),
            new DistrictSeed(81, "MERKEZ"),
            new DistrictSeed(81, "AKÇAKOCA"),
        };

        db.Districts.AddRange(districtSeeds
            .Where(d => cityMap.ContainsKey(d.PlateCode))
            .Select(d => new District
            {
                Name   = d.Name,
                CityId = cityMap[d.PlateCode]
            }));

        await db.SaveChangesAsync();
    }

    private record DistrictSeed(int PlateCode, string Name);

    // ─────────────────────────── Tax Offices ───────────────────────────────

    private static async Task SeedTaxOfficesAsync(AppDbContext db)
    {
        if (await db.TaxOffices.AnyAsync()) return;

        var cityMap = await db.Cities.ToDictionaryAsync(c => c.PlateCode, c => c.Id);

        var seeds = new[]
        {
            // ── İstanbul (34) ──
            new TaxOfficeSeed(34, "3401", "Adalar"),
            new TaxOfficeSeed(34, "3402", "Alibeyköy"),
            new TaxOfficeSeed(34, "3403", "Arnavutköy"),
            new TaxOfficeSeed(34, "3404", "Ataşehir"),
            new TaxOfficeSeed(34, "3405", "Avcılar"),
            new TaxOfficeSeed(34, "3406", "Avrupa Kurumlar"),
            new TaxOfficeSeed(34, "3407", "Bağcılar"),
            new TaxOfficeSeed(34, "3408", "Bahçelievler"),
            new TaxOfficeSeed(34, "3409", "Bakırköy"),
            new TaxOfficeSeed(34, "3410", "Başakşehir"),
            new TaxOfficeSeed(34, "3411", "Bayrampaşa"),
            new TaxOfficeSeed(34, "3412", "Beşiktaş"),
            new TaxOfficeSeed(34, "3413", "Beykoz"),
            new TaxOfficeSeed(34, "3414", "Beylikdüzü"),
            new TaxOfficeSeed(34, "3415", "Beyoğlu"),
            new TaxOfficeSeed(34, "3416", "Büyükçekmece"),
            new TaxOfficeSeed(34, "3417", "Çatalca"),
            new TaxOfficeSeed(34, "3418", "Esenler"),
            new TaxOfficeSeed(34, "3419", "Esenyurt"),
            new TaxOfficeSeed(34, "3420", "Eyüpsultan"),
            new TaxOfficeSeed(34, "3421", "Fatih"),
            new TaxOfficeSeed(34, "3422", "Gaziosmanpaşa"),
            new TaxOfficeSeed(34, "3423", "Güngören"),
            new TaxOfficeSeed(34, "3424", "İstanbul Büyük Mükellefler"),
            new TaxOfficeSeed(34, "3425", "Kadıköy"),
            new TaxOfficeSeed(34, "3426", "Kağıthane"),
            new TaxOfficeSeed(34, "3427", "Kartal"),
            new TaxOfficeSeed(34, "3428", "Küçükçekmece"),
            new TaxOfficeSeed(34, "3429", "Maltepe"),
            new TaxOfficeSeed(34, "3430", "Pendik"),
            new TaxOfficeSeed(34, "3431", "Sancaktepe"),
            new TaxOfficeSeed(34, "3432", "Sarıyer"),
            new TaxOfficeSeed(34, "3433", "Silivri"),
            new TaxOfficeSeed(34, "3434", "Sultanbeyli"),
            new TaxOfficeSeed(34, "3435", "Sultangazi"),
            new TaxOfficeSeed(34, "3436", "Şişli"),
            new TaxOfficeSeed(34, "3437", "Tuzla"),
            new TaxOfficeSeed(34, "3438", "Ümraniye"),
            new TaxOfficeSeed(34, "3439", "Üsküdar"),
            new TaxOfficeSeed(34, "3440", "Zeytinburnu"),

            // ── Ankara (06) ──
            new TaxOfficeSeed(6,  "0601", "Altındağ"),
            new TaxOfficeSeed(6,  "0602", "Ankara Büyük Mükellefler"),
            new TaxOfficeSeed(6,  "0603", "Batı"),
            new TaxOfficeSeed(6,  "0604", "Çankaya"),
            new TaxOfficeSeed(6,  "0605", "Doğu"),
            new TaxOfficeSeed(6,  "0606", "Etimesgut"),
            new TaxOfficeSeed(6,  "0607", "Gölbaşı"),
            new TaxOfficeSeed(6,  "0608", "Keçiören"),
            new TaxOfficeSeed(6,  "0609", "Mamak"),
            new TaxOfficeSeed(6,  "0610", "Polatlı"),
            new TaxOfficeSeed(6,  "0611", "Pursaklar"),
            new TaxOfficeSeed(6,  "0612", "Sincan"),
            new TaxOfficeSeed(6,  "0613", "Yenimahalle"),

            // ── İzmir (35) ──
            new TaxOfficeSeed(35, "3501", "Aliağa"),
            new TaxOfficeSeed(35, "3502", "Alsancak"),
            new TaxOfficeSeed(35, "3503", "Balçova"),
            new TaxOfficeSeed(35, "3504", "Bergama"),
            new TaxOfficeSeed(35, "3505", "Bornova"),
            new TaxOfficeSeed(35, "3506", "Buca"),
            new TaxOfficeSeed(35, "3507", "İzmir Büyük Mükellefler"),
            new TaxOfficeSeed(35, "3508", "Karabağlar"),
            new TaxOfficeSeed(35, "3509", "Karşıyaka"),
            new TaxOfficeSeed(35, "3510", "Kemalpaşa"),
            new TaxOfficeSeed(35, "3511", "Konak"),
            new TaxOfficeSeed(35, "3512", "Menemen"),
            new TaxOfficeSeed(35, "3513", "Ödemiş"),
            new TaxOfficeSeed(35, "3514", "Torbalı"),

            // ── Bursa (16) ──
            new TaxOfficeSeed(16, "1601", "Bursa Büyük Mükellefler"),
            new TaxOfficeSeed(16, "1602", "Gemlik"),
            new TaxOfficeSeed(16, "1603", "İnegöl"),
            new TaxOfficeSeed(16, "1604", "Mudanya"),
            new TaxOfficeSeed(16, "1605", "Mustafakemalpaşa"),
            new TaxOfficeSeed(16, "1606", "Nilüfer"),
            new TaxOfficeSeed(16, "1607", "Osmangazi"),
            new TaxOfficeSeed(16, "1608", "Yıldırım"),

            // ── Antalya (07) ──
            new TaxOfficeSeed(7,  "0701", "Alanya"),
            new TaxOfficeSeed(7,  "0702", "Gazipaşa"),
            new TaxOfficeSeed(7,  "0703", "Kepez"),
            new TaxOfficeSeed(7,  "0704", "Konyaaltı"),
            new TaxOfficeSeed(7,  "0705", "Kumluca"),
            new TaxOfficeSeed(7,  "0706", "Manavgat"),
            new TaxOfficeSeed(7,  "0707", "Muratpaşa"),
            new TaxOfficeSeed(7,  "0708", "Serik"),

            // ── Adana (01) ──
            new TaxOfficeSeed(1,  "0101", "Çukurova"),
            new TaxOfficeSeed(1,  "0102", "Kozan"),
            new TaxOfficeSeed(1,  "0103", "Seyhan"),
            new TaxOfficeSeed(1,  "0104", "Yüreğir"),

            // ── Gaziantep (27) ──
            new TaxOfficeSeed(27, "2701", "Gaziantep Büyük Mükellefler"),
            new TaxOfficeSeed(27, "2702", "İslahiye"),
            new TaxOfficeSeed(27, "2703", "Nizip"),
            new TaxOfficeSeed(27, "2704", "Şahinbey"),
            new TaxOfficeSeed(27, "2705", "Şehitkamil"),

            // ── Konya (42) ──
            new TaxOfficeSeed(42, "4201", "Ereğli"),
            new TaxOfficeSeed(42, "4202", "Karatay"),
            new TaxOfficeSeed(42, "4203", "Meram"),
            new TaxOfficeSeed(42, "4204", "Selçuklu"),

            // ── Kocaeli (41) ──
            new TaxOfficeSeed(41, "4101", "Gebze"),
            new TaxOfficeSeed(41, "4102", "Gölcük"),
            new TaxOfficeSeed(41, "4103", "İzmit"),
            new TaxOfficeSeed(41, "4104", "Kocaeli Büyük Mükellefler"),
            new TaxOfficeSeed(41, "4105", "Körfez"),

            // ── Mersin (33) ──
            new TaxOfficeSeed(33, "3301", "Akdeniz"),
            new TaxOfficeSeed(33, "3302", "Erdemli"),
            new TaxOfficeSeed(33, "3303", "Mezitli"),
            new TaxOfficeSeed(33, "3304", "Tarsus"),
            new TaxOfficeSeed(33, "3305", "Toroslar"),
            new TaxOfficeSeed(33, "3306", "Yenişehir"),

            // ── Hatay (31) ──
            new TaxOfficeSeed(31, "3101", "Antakya"),
            new TaxOfficeSeed(31, "3102", "Dörtyol"),
            new TaxOfficeSeed(31, "3103", "İskenderun"),
            new TaxOfficeSeed(31, "3104", "Kırıkhan"),

            // ── Manisa (45) ──
            new TaxOfficeSeed(45, "4501", "Akhisar"),
            new TaxOfficeSeed(45, "4502", "Alaşehir"),
            new TaxOfficeSeed(45, "4503", "Salihli"),
            new TaxOfficeSeed(45, "4504", "Turgutlu"),

            // ── Kayseri (38) ──
            new TaxOfficeSeed(38, "3801", "Kocasinan"),
            new TaxOfficeSeed(38, "3802", "Melikgazi"),
            new TaxOfficeSeed(38, "3803", "Talas"),

            // ── Eskişehir (26) ──
            new TaxOfficeSeed(26, "2601", "Odunpazarı"),
            new TaxOfficeSeed(26, "2602", "Tepebaşı"),

            // ── Diyarbakır (21) ──
            new TaxOfficeSeed(21, "2101", "Bağlar"),
            new TaxOfficeSeed(21, "2102", "Sur"),
            new TaxOfficeSeed(21, "2103", "Yenişehir"),

            // ── Sakarya (54) ──
            new TaxOfficeSeed(54, "5401", "Adapazarı"),
            new TaxOfficeSeed(54, "5402", "Arifiye"),
            new TaxOfficeSeed(54, "5403", "Hendek"),
            new TaxOfficeSeed(54, "5404", "Serdivan"),

            // ── Tekirdağ (59) ──
            new TaxOfficeSeed(59, "5901", "Çerkezköy"),
            new TaxOfficeSeed(59, "5902", "Çorlu"),
            new TaxOfficeSeed(59, "5903", "Kapaklı"),
            new TaxOfficeSeed(59, "5904", "Süleymanpaşa"),

            // ── Muğla (48) ──
            new TaxOfficeSeed(48, "4801", "Bodrum"),
            new TaxOfficeSeed(48, "4802", "Datça"),
            new TaxOfficeSeed(48, "4803", "Fethiye"),
            new TaxOfficeSeed(48, "4804", "Marmaris"),
            new TaxOfficeSeed(48, "4805", "Menteşe"),
            new TaxOfficeSeed(48, "4806", "Milas"),

            // ── Trabzon (61) ──
            new TaxOfficeSeed(61, "6101", "Akçaabat"),
            new TaxOfficeSeed(61, "6102", "Ortahisar"),

            // ── Samsun (55) ──
            new TaxOfficeSeed(55, "5501", "Atakum"),
            new TaxOfficeSeed(55, "5502", "Bafra"),
            new TaxOfficeSeed(55, "5503", "Canik"),
            new TaxOfficeSeed(55, "5504", "İlkadım"),

            // ── Denizli (20) ──
            new TaxOfficeSeed(20, "2001", "Merkezefendi"),
            new TaxOfficeSeed(20, "2002", "Pamukkale"),

            // ── Balıkesir (10) ──
            new TaxOfficeSeed(10, "1001", "Altıeylül"),
            new TaxOfficeSeed(10, "1002", "Bandırma"),
            new TaxOfficeSeed(10, "1003", "Edremit"),
            new TaxOfficeSeed(10, "1004", "Karesi"),

            // ── Kahramanmaraş (46) ──
            new TaxOfficeSeed(46, "4601", "Dulkadiroğlu"),
            new TaxOfficeSeed(46, "4602", "Onikişubat"),

            // ── Malatya (44) ──
            new TaxOfficeSeed(44, "4401", "Battalgazi"),
            new TaxOfficeSeed(44, "4402", "Yeşilyurt"),

            // ── Erzurum (25) ──
            new TaxOfficeSeed(25, "2501", "Aziziye"),
            new TaxOfficeSeed(25, "2502", "Palandöken"),
            new TaxOfficeSeed(25, "2503", "Yakutiye"),

            // ── Çanakkale (17) ──
            new TaxOfficeSeed(17, "1701", "Biga"),
            new TaxOfficeSeed(17, "1702", "Çan"),
            new TaxOfficeSeed(17, "1703", "Gelibolu"),
            new TaxOfficeSeed(17, "1704", "Merkez"),

            // ── Edirne (22) ──
            new TaxOfficeSeed(22, "2201", "Keşan"),
            new TaxOfficeSeed(22, "2202", "Merkez"),
            new TaxOfficeSeed(22, "2203", "Uzunköprü"),
        };

        db.TaxOffices.AddRange(seeds
            .Where(s => cityMap.ContainsKey(s.PlateCode))
            .Select(s => new TaxOffice
            {
                Code   = s.Code,
                Name   = s.Name,
                CityId = cityMap[s.PlateCode]
            }));

        await db.SaveChangesAsync();
    }

    private static async Task SeedMessageTemplatesAsync(AppDbContext db)
    {
        var existingNames = await db.MessageTemplates
            .Select(x => x.Name)
            .ToListAsync();

        var existingNameSet = new HashSet<string>(existingNames, StringComparer.OrdinalIgnoreCase);

        var specialDayNameMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["NEW_YEAR"] = "Yılbaşı",
            ["NATIONAL_SOVEREIGNTY_AND_CHILDREN"] = "Ulusal Egemenlik ve Çocuk Bayramı",
            ["LABOUR_DAY"] = "Emek ve Dayanışma Günü",
            ["ATATURK_MEMORIAL_YOUTH_SPORTS"] = "Atatürk'ü Anma, Gençlik ve Spor Bayramı",
            ["ATATURK_MEMORIAL_DAY"] = "Atatürk'ü Anma Günü",
            ["DEMOCRACY_AND_NATIONAL_UNITY"] = "Demokrasi ve Millî Birlik Günü",
            ["VICTORY_DAY"] = "Zafer Bayramı",
            ["REPUBLIC_DAY"] = "Cumhuriyet Bayramı",
            ["VALENTINES_DAY"] = "Sevgililer Günü",
            ["WOMENS_DAY"] = "Dünya Kadınlar Günü",
            ["MOTHERS_DAY"] = "Anneler Günü",
            ["FATHERS_DAY"] = "Babalar Günü",
            ["RAMADAN_FEAST_DAY1"] = "Ramazan Bayramı 1. Gün",
            ["RAMADAN_FEAST_DAY2"] = "Ramazan Bayramı 2. Gün",
            ["RAMADAN_FEAST_DAY3"] = "Ramazan Bayramı 3. Gün",
            ["SACRIFICE_FEAST_DAY1"] = "Kurban Bayramı 1. Gün",
            ["SACRIFICE_FEAST_DAY2"] = "Kurban Bayramı 2. Gün",
            ["SACRIFICE_FEAST_DAY3"] = "Kurban Bayramı 3. Gün",
            ["SACRIFICE_FEAST_DAY4"] = "Kurban Bayramı 4. Gün"
        };

        var dbSpecialDays = await db.SpecialDays
            .Where(x => x.DeletedAt == null)
            .Select(x => new { x.EventCode, x.Name })
            .Distinct()
            .ToListAsync();

        foreach (var day in dbSpecialDays)
        {
            if (string.IsNullOrWhiteSpace(day.EventCode) || string.IsNullOrWhiteSpace(day.Name))
                continue;

            if (!specialDayNameMap.ContainsKey(day.EventCode))
                specialDayNameMap[day.EventCode] = day.Name.Trim();
        }

        var toAdd = new List<MessageTemplate>();

        foreach (var day in specialDayNameMap.OrderBy(x => x.Value))
        {
            var templateName = $"SMS Şablonu - {day.Value}";
            if (existingNameSet.Contains(templateName))
                continue;

            var template = new MessageTemplate
            {
                Name = templateName,
                ChannelType = MessageChannelType.Sms,
                SmsText = $"Sayın {{FirstName}} {{LastName}}, {day.Value} kutlu olsun. PulsePoll ailesi olarak iyi günler dileriz.",
                IsActive = true
            };
            template.SetCreated(0);
            toAdd.Add(template);
            existingNameSet.Add(templateName);
        }

        const string birthdayTemplateName = "SMS Şablonu - Doğum Günü";
        if (!existingNameSet.Contains(birthdayTemplateName))
        {
            var birthdayTemplate = new MessageTemplate
            {
                Name = birthdayTemplateName,
                ChannelType = MessageChannelType.Sms,
                SmsText = "Sayın {FirstName} {LastName}, doğum gününüz kutlu olsun. Sağlıklı ve mutlu yıllar dileriz.",
                IsActive = true
            };
            birthdayTemplate.SetCreated(0);
            toAdd.Add(birthdayTemplate);
        }

        if (toAdd.Count == 0)
            return;

        db.MessageTemplates.AddRange(toAdd);
        await db.SaveChangesAsync();
    }

    private record TaxOfficeSeed(int PlateCode, string Code, string Name);
}
