using PulsePoll.Domain.Enums;

namespace PulsePoll.Application.DTOs;

public record ProjectDto(
    int Id,
    int CustomerId,
    string CustomerShortName,
    string Code,
    string Name,
    string? Description,
    string? Category,
    int ParticipantCount,
    int TotalTargetCount,
    int DurationDays,
    DateOnly? StartDate,
    DateOnly? EndDate,
    decimal Budget,
    decimal Reward,
    decimal ConsolationReward,
    string SurveyUrl,
    string SubjectParameterName,
    string ProjectParameterName,
    int EstimatedMinutes,
    string? CustomerBriefing,
    string StartMessage,
    string CompletedMessage,
    string DisqualifyMessage,
    string QuotaFullMessage,
    string ScreenOutMessage,
    ProjectStatus Status,
    AssignmentStatus? AssignmentStatus,
    int? CoverMediaId,
    string? CoverImageUrl,
    bool IsScheduledDistribution = false,
    TimeOnly DistributionStartHour = default,
    TimeOnly DistributionEndHour = default,
    string RewardUnitCode = "TRY",
    string RewardUnitLabel = "TL",
    decimal RewardUnitTryMultiplier = 1m);

public record CreateProjectDto(
    int CustomerId,
    string Code,
    string Name,
    string? Description,
    string? Category,
    int ParticipantCount,
    int TotalTargetCount,
    int DurationDays,
    DateOnly? StartDate,
    decimal Budget,
    decimal Reward,
    decimal ConsolationReward,
    string SurveyUrl,
    string SubjectParameterName,
    string ProjectParameterName,
    int EstimatedMinutes,
    string? CustomerBriefing,
    string StartMessage,
    string CompletedMessage,
    string DisqualifyMessage,
    string QuotaFullMessage,
    string ScreenOutMessage,
    int? CoverMediaId = null,
    bool IsScheduledDistribution = false,
    TimeOnly DistributionStartHour = default,
    TimeOnly DistributionEndHour = default);

public record UpdateProjectDto(
    string Name,
    string? Description,
    string? Category,
    int ParticipantCount,
    int TotalTargetCount,
    int DurationDays,
    DateOnly? StartDate,
    decimal Budget,
    decimal Reward,
    decimal ConsolationReward,
    string SurveyUrl,
    string SubjectParameterName,
    string ProjectParameterName,
    int EstimatedMinutes,
    string? CustomerBriefing,
    string StartMessage,
    string CompletedMessage,
    string DisqualifyMessage,
    string QuotaFullMessage,
    string ScreenOutMessage,
    ProjectStatus Status,
    int? CoverMediaId = null,
    bool IsScheduledDistribution = false,
    TimeOnly DistributionStartHour = default,
    TimeOnly DistributionEndHour = default);
